[template]
src	= "haproxy.cfg"
dest	= "/etc/haproxy/haproxy.cfg"
keys	= [
    "services",
    "config",
]
check_cmd       = "haproxy -c -f {{ .src }}"
reload_cmd 	= "haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf $(cat /var/run/haproxy.pid)"
